version: "3.9"

services:
  frontend:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile.frontend
    env_file:
      - .env.docker
    ports:
      - 3000:3000
    volumes:
      - ./:/oh
      - /oh/node_modules
      - /oh/build
      - /oh/docs
    depends_on:
      - backend
    networks:
      - openhospital
    stdin_open: true

  backend:
    build:
      context: ./docker
      dockerfile: Dockerfile.backend
    env_file:
      - .env.docker
    ports:
      - "8080:8080"
    depends_on:
      - database
    networks:
      - openhospital

  database:
    build:
      context: ./docker
      dockerfile: Dockerfile.database
    env_file:
      - .env.docker
    ports:
      - "3306:3306"
    command: mysqld --sql_mode="STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION" --lower_case_table_names=1
    networks:
      - openhospital

  db-admin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 9000:80
    env_file:
      - .env.docker
    environment:
      PMA_HOST: "database"
      PMA_PORT: 3306
      PMA_USER: "root"
      PMA_PASSWORD: "root"
    depends_on:
      - database
    networks:
      - openhospital

networks:
  openhospital:
