version: "3.9"

services:
  backend:
    build:
      context: ./docker
    environment:
      GITHUB_ORG: intesys
      OH_CORE_BRANCH: develop
      OH_API_BRANCH: develop
    ports:
      - "8080:8080"
    depends_on:
      - database
    networks:
      - openhospital

  database:
    build:
      context: ./docker
      dockerfile: Dockerfile.database
    image: oh-core_database:latest
    environment:
      GITHUB_ORG: intesys
      OH_CORE_BRANCH: develop
    ports:
      - "3306:3306"
    command: mysqld --sql_mode="STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION" --lower_case_table_names=1
    networks:
      - openhospital

networks:
  openhospital:
