name: Deploy

on:
  push:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Installing...
        run: npm i
      - name: Building...
        env:
          CI: false
        run: npm run build:gh-pages
      - name: Deploying on GH Pages...
        run: npm run deploy:gh-page