name: Deploy

on:
  push:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: fregante/setup-git-user@v1
      - name: Installing...
        run: npm i
      - name: Building...
        run: npm run build:gh-pages
      - run: git add --force build
      - run: git commit -m 'new build' 
      - run: echo "HASH_COMMIT=$(git subtree split --quiet --prefix build develop)" >> $HASH_COMMIT
      - run: git push intesys-oh $HASH_COMMIT:gh-pages --force